[variables]
NODE_VERSION = "22"

[phases.setup]
nixPkgs = ["nodejs_22", "npm"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npx serve -s dist -l $PORT"
